#服务端口
server:
  port: 8201
  address: 0.0.0.0   # 允许局域网访问
spring:
#服务名
  application:
    name: service-company
#环境设置
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB     #单个文件最大限制
      max-request-size: 50MB  #多个文件最大限制
#mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.53.181:3306/recruitment_company?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#返回json全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #nacos
  cloud:
    nacos:
      server-addr: 43.139.53.181:8848
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#feign:
#  httpclient:
#    connection-timeout: 30000
#    connection-timer-repeat: 30000
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000